"""
Module: music.domain.ports

Purpose:
    Declare Protocol interfaces (ports) for LunaWave's hexagonal architecture.

Responsibilities:
    - Define AudioPlayerPort, MediaExtractorPort, and TrackRepositoryPort.
    - Declare session, lyrics, and sponsorblock provider protocols.

Depends on:
    - music.domain.state (TrackInfo)
    - lunawave_framework.core.kernel.latency_window (type-checking only)

Subscribes to:
    None

Publishes:
    None

Thread Safety:
    Stateless (interface definitions only).

Phase 4 extraction note:
    Per ADR 0013 Decision 2 and ADR 0014 (docs/adr/0014-persistence-split.md):
    SessionRepositoryPort was deliberately kept here through Phase 3 since
    its implementation (persistence.session_repo) hadn't moved yet and
    DatabasePort composes it together with TrackRepositoryPort/
    ArtistRepositoryPort (both music-domain). Phase 4 moved the
    implementation to lunawave_framework.core.storage.session_repo, so
    SessionRepositoryPort now lives there too (core/storage/ports.py) and
    is only re-exported here for backward compatibility -- DatabasePort
    still composes it, it just now pulls in a framework type instead of a
    locally-defined one.
"""

from collections.abc import Callable
from typing import TYPE_CHECKING, Any, Protocol

from lunawave_framework.core.storage.ports import SessionRepositoryPort

if TYPE_CHECKING:
    from lunawave_framework.core.kernel.latency_window import LatencyWindow

from music.domain.state import TrackInfo


class AudioPlayerPort(Protocol):
    @property
    def is_connected(self) -> bool: ...

    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def play(self, uri: str) -> None: ...
    async def pause(self) -> None: ...
    async def resume(self) -> None: ...
    async def stop(self) -> None: ...
    async def set_volume(self, volume: int) -> None: ...
    async def set_af(self, filter_str: str) -> None: ...
    async def seek(self, position: float) -> None: ...
    async def set_property(self, name: str, value: Any) -> None: ...
    async def get_duration(self) -> float: ...
    async def get_position(self) -> float: ...
    async def toggle_pause(self) -> None: ...


class MediaExtractorPort(Protocol):
    async def search(self, query: str, max_results: int = 15) -> list[TrackInfo]: ...
    async def extract_info(self, url: str) -> TrackInfo | None: ...
    async def get_stream_url(self, video_id: str) -> str | None: ...
    async def download_mp3(self, video_id: str, on_progress: Callable | None = None) -> str: ...
    async def download_audio(self, video_id: str, on_progress: Callable | None = None) -> str: ...
    def cancel_download(self) -> None: ...


class StreamResolverPort(Protocol):
    @property
    def db(self) -> "DatabasePort": ...
    @property
    def latency_window(self) -> "LatencyWindow": ...
    async def resolve(self, track: TrackInfo) -> str: ...


class TrackRepositoryPort(Protocol):
    async def upsert_track(
        self, track: TrackInfo, stream_url: str | None = None, local_path: str | None = None
    ) -> None: ...
    async def update_stream_url_only(self, video_id: str, stream_url: str) -> None: ...
    async def get_track(self, video_id: str) -> TrackInfo | None: ...
    async def increment_play_count(self, video_id: str) -> None: ...
    async def set_loudness(
        self, video_id: str, lufs: float, true_peak: float | None = None
    ) -> None: ...
    async def set_last_position(self, video_id: str, position: float) -> None: ...
    async def mark_unavailable(self, track: TrackInfo, reason: str) -> None: ...
    async def get_unavailable_reason(self, video_id: str) -> str | None: ...


class ArtistRepositoryPort(Protocol):
    @property
    def conn(self) -> Any: ...

    async def get_all_artists(self, kategori: str | None = None) -> list[str]: ...
    async def get_artist_songs_strict(self, artist: str, limit: int = 10) -> list[TrackInfo]: ...
    async def record_completion(self, artist_name: str) -> None: ...
    async def record_skip(self, artist_name: str) -> None: ...
    async def get_reward_stats(self) -> dict[str, tuple[float, float]]: ...


class LibraryRepositoryPort(Protocol):
    @property
    def conn(self) -> Any: ...

    async def get_random_songs(
        self,
        limit: int = 12,
        exclude_ids: set[str] | None = None,
        artists: list[str] | None = None,
        max_per_artist: int | None = None,
    ) -> list[TrackInfo]: ...


class DiscoverRepositoryPort(Protocol):
    async def get_bandit_ranked_artists(self, n: int) -> list[dict[str, Any]]: ...
    async def get_unheard_artists(self, n: int) -> list[dict[str, Any]]: ...
    async def get_top_genre(self) -> str | None: ...
    async def get_genre_artists_enriched(self, genre: str, n: int) -> list[dict[str, Any]]: ...
    async def get_taste_spectrum(self) -> list[dict[str, Any]]: ...
    async def get_artist_detail(self, nama: str) -> dict[str, Any] | None: ...


class DatabasePort(TrackRepositoryPort, SessionRepositoryPort, ArtistRepositoryPort, Protocol):
    async def init(self) -> None: ...
    async def close(self) -> None: ...
    async def get_bandit_ranked_artists(self, n: int) -> list[dict[str, Any]]: ...
    async def get_unheard_artists(self, n: int) -> list[dict[str, Any]]: ...
    async def get_top_genre(self) -> str | None: ...
    async def get_genre_artists_enriched(self, genre: str, n: int) -> list[dict[str, Any]]: ...
    async def get_taste_spectrum(self) -> list[dict[str, Any]]: ...
    async def get_artist_detail(self, nama: str) -> dict[str, Any] | None: ...


class LyricsProvider(Protocol):
    async def fetch(self, track: TrackInfo) -> None: ...


class SponsorBlockProvider(Protocol):
    async def fetch_segments(self, video_id: str) -> None: ...
